# Generated by Django 2.1 on 2021-08-19 15:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0003_planoterapeutico_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoterapeutico',
            name='round',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
